# Generated by Django 4.0.6 on 2022-07-23 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('dueDate', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=128)),
                ('urgency', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='size_options',
            field=models.CharField(choices=[('xl', 'xl'), ('l', 'l'), ('s', 's')], default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(),
        ),
    ]
